fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\Admin\User
    from_email:
        address: "bonjour@charliebreval.com"
        sender_name: "bonjour@charliebreval.com"

