swiftmailer:
    transport: "smtp"
    auth_mode: "login"
    host:      "ns0.ovh.net"
    encryption: null
    port:      "587"
    username:  "bonjour@charliebreval.com"
    password:  "Tyranides25"
    spool:     { type: memory }
